apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-rbac-permissions
  annotations:
    package-operator.run/phase: rbac-permissions-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-rbac-permissions
  annotations:
    package-operator.run/phase: rbac-permissions-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-rbac-permissions
  annotations:
    package-operator.run/phase: rbac-permissions-operator
roleRef:
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: rbac-permissions-operator-registry
  namespace: openshift-rbac-permissions
  annotations:
    package-operator.run/phase: rbac-permissions-operator
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
          weight: 1
  displayName: RBAC Permissions Operator
  grpcPodConfig:
    nodeSelector:
      node-role.kubernetes.io: infra
    securityContextConfig: restricted
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/app-sre/rbac-permissions-operator-registry@sha256:d50bf707dd619a265b190dbec5b6af3e3f07ce4d7f467894b6561cf4070eed30
  publisher: Red Hat
  sourceType: grpc
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rbac-permissions-operator
  namespace: openshift-rbac-permissions
  annotations:
    package-operator.run/phase: rbac-permissions-operator
spec:
  channel: staging
  name: rbac-permissions-operator
  source: rbac-permissions-operator-registry
  sourceNamespace: openshift-rbac-permissions
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.operatorframework.io/exclude-global-namespace-resolution: "true"
    package-operator.run/phase: rbac-permissions-operator
  name: rbac-permissions-operator
  namespace: openshift-rbac-permissions
spec:
  targetNamespaces:
    - openshift-rbac-permissions
