#!/usr/bin/env bash

set -e

OPERATOR=$1
COMMIT=$2
TEMPLATE=https://raw.githubusercontent.com/openshift/${OPERATOR}/${COMMIT}/hack/olm-registry/olm-artifacts-template.yaml

# TODO: values should come from operator build pipeline
REGISTRY_IMG=quay.io/app-sre/${OPERATOR}-registry
IMAGE_TAG=staging-latest
IMAGE_DIGEST=$(skopeo inspect --format '{{.Digest}}' docker://${REGISTRY_IMG}:${IMAGE_TAG} | tr -d "\r")
CHANNEL=${IMAGE_TAG%%-*}

_OUTDIR=resources/${OPERATOR}
_BUNDLE_REGISTRY=ghcr.io/jbpratt/managed-openshift/release-bundle

mkdir -p ${_OUTDIR}

# download template
_RAW_TEMPLATE=$(curl -sL ${TEMPLATE} | sed 's/apiVersion: v1/apiVersion: template.openshift.io\/v1/')

# process the template
_PROCESSED_TEMPLATE=$(oc process \
	--local \
	--output=yaml \
	--ignore-unknown-parameters \
	--filename \
	${TEMPLATE} \
	REGISTRY_IMG=${REGISTRY_IMG} \
	CHANNEL=${CHANNEL} \
	IMAGE_TAG=${IMAGE_TAG} \
	IMAGE_DIGEST=${IMAGE_DIGEST} <<<${_RAW_TEMPLATE})

# append the package-operator.run/phase to each resource and write out file
yq '
    .items[0].spec.resources[].metadata.annotations += {"package-operator.run/phase":"deploy"} |
    .items[0].spec.resources[] |
    split_doc' <<<${_PROCESSED_TEMPLATE} >${_OUTDIR}/resources.yaml

if git diff --quiet --exit-code --cached; then
	echo "No changes" && exit 1
fi

# commit changes
git add ${_OUTDIR}
git commit -m "${OPERATOR}: ${COMMIT:1:7}"
# git push

_BRANCH=$(git rev-parse --abbrev-ref HEAD)
_COMMIT=$(git rev-parse --short HEAD)
# TODO: How to determine the build#?
# _BUILD_NUMBER=

# package with PKO
kubectl package build --push --tag ${_BUNDLE_REGISTRY}:${_BRANCH/#release-/}-${_COMMIT} ./resources
