#!/usr/bin/env bash

set -e

_BUNDLE_REGISTRY=ghcr.io/jbpratt/managed-openshift/release-bundle

OPERATOR=$1
COMMIT=$2
TEMPLATE=https://raw.githubusercontent.com/openshift/${OPERATOR}/${COMMIT}/hack/olm-registry/olm-artifacts-template.yaml

# TODO: values should come from operator build pipeline
REGISTRY_IMG=quay.io/app-sre/${OPERATOR}-registry
IMAGE_TAG=staging-latest
IMAGE_DIGEST=$(skopeo inspect --format '{{.Digest}}' docker://"${REGISTRY_IMG}":"${IMAGE_TAG}" | tr -d "\r")
CHANNEL=${IMAGE_TAG%%-*}

_OUTDIR=resources/${OPERATOR}
rm -rf "${_OUTDIR}" && mkdir -p "${_OUTDIR}"

echo "Downloading template..."
_RAW_TEMPLATE=$(curl -sL "${TEMPLATE}" | sed 's/apiVersion: v1/apiVersion: template.openshift.io\/v1/')

echo "Process template with parameters..."
_PROCESSED_TEMPLATE=$(oc process \
	--local \
	--output=yaml \
	--ignore-unknown-parameters \
	--filename \
	"${TEMPLATE}" \
	REGISTRY_IMG="${REGISTRY_IMG}" \
	CHANNEL="${CHANNEL}" \
	IMAGE_TAG="${IMAGE_TAG}" \
	IMAGE_DIGEST="${IMAGE_DIGEST}" <<<"${_RAW_TEMPLATE}")

echo "Appending 'package-operator.run/phase' to every object and writing to ${_OUTDIR} ..."
yq "
    .items[0].spec.resources[] |
    .metadata.annotations += {\"package-operator.run/phase\":\"${OPERATOR}\"} |
    split_doc" <<<"${_PROCESSED_TEMPLATE}" >"${_OUTDIR}"/resources.yaml

# add new operator phase if it doesn't exist
if ! grep -q "${OPERATOR}" resources/manifest.yaml; then
	yq -i ".spec.phases += {\"name\": \"${OPERATOR}\"}" resources/manifest.yaml
fi

git add "${_OUTDIR}" resources/manifest.yaml

if git diff --quiet --exit-code --cached; then
	echo "No changes" && exit 1
fi

echo "Committing changes..."
git commit -m "${OPERATOR}: ${COMMIT:1:7}"
# git push

_BRANCH=$(git rev-parse --abbrev-ref HEAD)
_COMMIT=$(git rev-parse --short HEAD)
_BUILD_NUMBER=$(git rev-list "$(git rev-list --parents HEAD | grep -E "^[a-f0-9]{40}$$")"..HEAD --count)
_TAG=${_BUNDLE_REGISTRY}:${_BRANCH/#release-/}-${_BUILD_NUMBER}-${_COMMIT}

echo "Building and pushing package ${_TAG} ..."
kubectl package build --push --tag "${_TAG}" ./resources
