apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-osd-metrics
  annotations:
    package-operator.run/phase: osd-metrics-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-osd-metrics
  annotations:
    package-operator.run/phase: osd-metrics-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-osd-metrics
  annotations:
    package-operator.run/phase: osd-metrics-exporter
roleRef:
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: osd-metrics-exporter-registry
  namespace: openshift-osd-metrics
  annotations:
    package-operator.run/phase: osd-metrics-exporter
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
          weight: 1
  displayName: OSD Metrics Exporter
  grpcPodConfig:
    nodeSelector:
      node-role.kubernetes.io: infra
    securityContextConfig: restricted
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/app-sre/osd-metrics-exporter-registry@sha256:1e23f9bb6a9a42bc4046d10f1e6a2693f38a8580cdfbabf279573f74998c4ae0
  publisher: Red Hat
  sourceType: grpc
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: osd-metrics-exporter
  namespace: openshift-osd-metrics
  annotations:
    package-operator.run/phase: osd-metrics-exporter
spec:
  channel: staging
  name: osd-metrics-exporter
  source: osd-metrics-exporter-registry
  sourceNamespace: openshift-osd-metrics
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.operatorframework.io/exclude-global-namespace-resolution: "true"
    package-operator.run/phase: osd-metrics-exporter
  name: osd-metrics-exporter
  namespace: openshift-osd-metrics
spec:
  targetNamespaces:
    - openshift-osd-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osd-metrics-exporter-watch-configmaps
  namespace: openshift-config
  annotations:
    package-operator.run/phase: osd-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-metrics-exporter-watch-configmaps
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: osd-metrics-exporter
    namespace: openshift-osd-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-metrics-exporter-watch-configmaps
  namespace: openshift-config
  annotations:
    package-operator.run/phase: osd-metrics-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-metrics-exporter
  namespace: openshift-machine-api
  annotations:
    package-operator.run/phase: osd-metrics-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osd-metrics-exporter
  namespace: openshift-machine-api
  annotations:
    package-operator.run/phase: osd-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-metrics-exporter
subjects:
  - kind: ServiceAccount
    name: osd-metrics-exporter
    namespace: openshift-osd-metrics
