apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: managed-openshift-release-bundle
spec:
  scopes:
    - Namespaced
    - Cluster
  phases:
    - name: managed-upgrade-operator
    - name: ocm-agent-operator
    - name: route-monitor-operator
    - name: must-gather-operator
    - name: osd-metrics-exporter
