apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: managed-openshift-release-bundle
spec:
  scopes:
    - Namespaced
    - Cluster
  phases:
    - name: managed-upgrade-operator
    - name: ocm-agent-operator
    - name: route-monitor-operator
    - name: must-gather-operator
    - name: osd-metrics-exporter
    - name: rbac-permissions-operator
  config:
    openAPIV3Schema:
      properties:
        api.openshift.com/sts:
          description: denoting whether the cluster is STS
          type: boolean
          default: false
        api.openshift.com/private-link:
          description: denoting whether the cluster is privatelink
          type: boolean
          default: false
        api.openshift.com/fedramp:
          description: denoting whether the cluster is fedramp
          type: boolean
          default: false
      type: object
