apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-must-gather-operator
  annotations:
    package-operator.run/phase: must-gather-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: must-gather-operator-registry
  namespace: openshift-must-gather-operator
  annotations:
    package-operator.run/phase: must-gather-operator
spec:
  displayName: must-gather-operator
  grpcPodConfig:
    nodeSelector:
      node-role.kubernetes.io: infra
    securityContextConfig: restricted
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/app-sre/must-gather-operator-registry@sha256:5b3c921406e9c90f4da393e7711b95897e1c2076964cf2f2e563629f3fc3b0a2
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: must-gather-operator
  namespace: openshift-must-gather-operator
  annotations:
    package-operator.run/phase: must-gather-operator
spec:
  channel: staging
  name: must-gather-operator
  source: must-gather-operator-registry
  sourceNamespace: openshift-must-gather-operator
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.operatorframework.io/exclude-global-namespace-resolution: "true"
    package-operator.run/phase: must-gather-operator
  name: must-gather-operator
  namespace: openshift-must-gather-operator
spec:
  targetNamespaces:
    - openshift-must-gather-operator
