apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
  name: openshift-custom-domains-operator
  annotations:
    package-operator.run/phase: deploy
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: custom-domains-operator-registry
  namespace: openshift-custom-domains-operator
  annotations:
    package-operator.run/phase: deploy
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
          weight: 1
  displayName: Custom Domains Operator
  grpcPodConfig:
    nodeSelector:
      node-role.kubernetes.io: infra
    securityContextConfig: restricted
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/app-sre/custom-domains-operator-registry@sha256:3bf3084ed5314841118e05345a03291eb33ab21a2dab66cb146dce01ecd10992
  publisher: Red Hat
  sourceType: grpc
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: custom-domains-operator
  namespace: openshift-custom-domains-operator
  annotations:
    package-operator.run/phase: deploy
spec:
  channel: staging
  name: custom-domains-operator
  source: custom-domains-operator-registry
  sourceNamespace: openshift-custom-domains-operator
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.operatorframework.io/exclude-global-namespace-resolution: "true"
    package-operator.run/phase: deploy
  name: custom-domains-operator
  namespace: openshift-custom-domains-operator
spec:
  targetNamespaces:
    - openshift-custom-domains-operator
