apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: managed-upgrade-operator-catalog
  namespace: openshift-managed-upgrade-operator
  annotations:
    package-operator.run/phase: managed-upgrade-operator
spec:
  displayName: Managed Upgrade Operator
  grpcPodConfig:
    nodeSelector:
      node-role.kubernetes.io: infra
    securityContextConfig: restricted
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  image: quay.io/app-sre/managed-upgrade-operator-registry@sha256:3ab12789f3392d2a574588ad79cf7fda388fd3b9e53f3de94b0fe53e9603dd57
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.operatorframework.io/exclude-global-namespace-resolution: "true"
    package-operator.run/phase: managed-upgrade-operator
  name: managed-upgrade-operator-og
  namespace: openshift-managed-upgrade-operator
spec:
  targetNamespaces:
    - openshift-managed-upgrade-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: managed-upgrade-operator
  namespace: openshift-managed-upgrade-operator
  annotations:
    package-operator.run/phase: managed-upgrade-operator
spec:
  channel: staging
  name: managed-upgrade-operator
  source: managed-upgrade-operator-catalog
  sourceNamespace: openshift-managed-upgrade-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: muo-monitoring-reader
  namespace: openshift-monitoring
  annotations:
    package-operator.run/phase: managed-upgrade-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - serviceaccounts
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: muo-pullsecret-reader
  namespace: openshift-config
  annotations:
    package-operator.run/phase: managed-upgrade-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: muo-monitoring-reader
  namespace: openshift-monitoring
  annotations:
    package-operator.run/phase: managed-upgrade-operator
roleRef:
  kind: Role
  name: muo-monitoring-reader
subjects:
  - kind: ServiceAccount
    name: managed-upgrade-operator
    namespace: openshift-managed-upgrade-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: muo-pullsecret-reader
  namespace: openshift-config
  annotations:
    package-operator.run/phase: managed-upgrade-operator
roleRef:
  kind: Role
  name: muo-pullsecret-reader
subjects:
  - kind: ServiceAccount
    name: managed-upgrade-operator
    namespace: openshift-managed-upgrade-operator
