apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
  name: openshift-ocm-agent-operator
  annotations:
    package-operator.run/phase: deploy
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ocm-agent-operator-registry
  namespace: openshift-ocm-agent-operator
  annotations:
    package-operator.run/phase: deploy
spec:
  displayName: OCM Agent Operator
  grpcPodConfig:
    nodeSelector:
      node-role.kubernetes.io: infra
    securityContextConfig: restricted
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  image: quay.io/app-sre/ocm-agent-operator-registry@sha256:42a05fabce933f0beae64a2c4cc523a734cc62d4284e637c06c8faf818adf8d4
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.operatorframework.io/exclude-global-namespace-resolution: "true"
    package-operator.run/phase: deploy
  name: ocm-agent-operator-og
  namespace: openshift-ocm-agent-operator
spec:
  targetNamespaces:
    - openshift-ocm-agent-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocm-agent-operator
  namespace: openshift-ocm-agent-operator
  annotations:
    package-operator.run/phase: deploy
spec:
  channel: staging
  name: ocm-agent-operator
  source: ocm-agent-operator-registry
  sourceNamespace: openshift-ocm-agent-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oao-openshiftconfig-reader
  namespace: openshift-config
  annotations:
    package-operator.run/phase: deploy
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oao-openshiftconfig-reader
  namespace: openshift-config
  annotations:
    package-operator.run/phase: deploy
roleRef:
  kind: Role
  name: oao-openshiftconfig-reader
subjects:
  - kind: ServiceAccount
    name: ocm-agent-operator
    namespace: openshift-ocm-agent-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oao-monitoring-manager
  namespace: openshift-monitoring
  annotations:
    package-operator.run/phase: deploy
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oao-monitoring-manager
  namespace: openshift-monitoring
  annotations:
    package-operator.run/phase: deploy
roleRef:
  kind: Role
  name: oao-monitoring-manager
subjects:
  - kind: ServiceAccount
    name: ocm-agent-operator
    namespace: openshift-ocm-agent-operator
